name: pjd
favicon: null
layout_spectrum: 0.44421644718386233
typography_spectrum: 0.22002087393775582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48499999684281647
  lightness: 0.19868092681281269
  saturation: 0.4217882838565856
  rhythmicContrast: 0.30432921345345676
purpose: []
